import type { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = "https://www.srikalavedika.com";

  return [
    { url: baseUrl, lastModified: new Date(), priority: 1.0 },
    { url: `${baseUrl}/about`, lastModified: new Date(), priority: 0.9 },
    { url: `${baseUrl}/services`, lastModified: new Date(), priority: 0.9 },
    { url: `${baseUrl}/admissions`, lastModified: new Date(), priority: 0.9 },
    { url: `${baseUrl}/contact`, lastModified: new Date(), priority: 0.8 },
    { url: `${baseUrl}/blog`, lastModified: new Date(), priority: 0.8 },
    { url: `${baseUrl}/gallery`, lastModified: new Date(), priority: 0.8 },
    // Services subpages
    { url: `${baseUrl}/services/carnatic-vocal`, lastModified: new Date(), priority: 0.7 },
    { url: `${baseUrl}/services/hindustani-vocal`, lastModified: new Date(), priority: 0.7 },
    { url: `${baseUrl}/services/bhajans`, lastModified: new Date(), priority: 0.7 },
    { url: `${baseUrl}/services/light-music`, lastModified: new Date(), priority: 0.7 },
    { url: `${baseUrl}/services/beat-boxing`, lastModified: new Date(), priority: 0.7 },
    { url: `${baseUrl}/services/bharatanatyam`, lastModified: new Date(), priority: 0.7 },
    { url: `${baseUrl}/services/kuchipudi`, lastModified: new Date(), priority: 0.7 },
    { url: `${baseUrl}/services/kathak`, lastModified: new Date(), priority: 0.7 },
    { url: `${baseUrl}/services/bollywood-dance`, lastModified: new Date(), priority: 0.7 },
    { url: `${baseUrl}/services/semi-classical-dance`, lastModified: new Date(), priority: 0.7 },
    { url: `${baseUrl}/services/hip-hop-dance`, lastModified: new Date(), priority: 0.7 },
    { url: `${baseUrl}/services/violin`, lastModified: new Date(), priority: 0.7 },
    { url: `${baseUrl}/services/keyboard`, lastModified: new Date(), priority: 0.7 },
    { url: `${baseUrl}/services/mridangam`, lastModified: new Date(), priority: 0.7 },
    { url: `${baseUrl}/services/flute`, lastModified: new Date(), priority: 0.7 },
    { url: `${baseUrl}/services/guitar`, lastModified: new Date(), priority: 0.7 },
    { url: `${baseUrl}/services/drawing`, lastModified: new Date(), priority: 0.7 },
    { url: `${baseUrl}/services/painting`, lastModified: new Date(), priority: 0.7 },
    { url: `${baseUrl}/services/creative-art`, lastModified: new Date(), priority: 0.7 },
    { url: `${baseUrl}/services/chess`, lastModified: new Date(), priority: 0.7 },
    { url: `${baseUrl}/services/rubiks-cube`, lastModified: new Date(), priority: 0.7 },
    { url: `${baseUrl}/services/vedic-maths`, lastModified: new Date(), priority: 0.7 },
    { url: `${baseUrl}/services/cultural-events`, lastModified: new Date(), priority: 0.7 },
    { url: `${baseUrl}/services/recitals`, lastModified: new Date(), priority: 0.7 },
    { url: `${baseUrl}/services/masterclasses`, lastModified: new Date(), priority: 0.7 },
    { url: `${baseUrl}/services/summer-camps`, lastModified: new Date(), priority: 0.7 },
    { url: `${baseUrl}/services/art-camps`, lastModified: new Date(), priority: 0.7 },
    { url: `${baseUrl}/services/annual-day`, lastModified: new Date(), priority: 0.7 },
    { url: `${baseUrl}/services/online-classes`, lastModified: new Date(), priority: 0.7 },
    { url: `${baseUrl}/services/private-training`, lastModified: new Date(), priority: 0.7 },
    { url: `${baseUrl}/services/personality-development`, lastModified: new Date(), priority: 0.7 },
    { url: `${baseUrl}/services/stage-confidence`, lastModified: new Date(), priority: 0.7 },
    { url: `${baseUrl}/services/leadership-skills`, lastModified: new Date(), priority: 0.7 },
    { url: `${baseUrl}/services/logical-reasoning`, lastModified: new Date(), priority: 0.7 },
    { url: `${baseUrl}/services/memory-techniques`, lastModified: new Date(), priority: 0.7 },
    { url: `${baseUrl}/services/certification`, lastModified: new Date(), priority: 0.7 },
    { url: `${baseUrl}/services/abacus`, lastModified: new Date(), priority: 0.7 },
    { url: `${baseUrl}/services/theatre`, lastModified: new Date(), priority: 0.7 },
    { url: `${baseUrl}/services/storytelling`, lastModified: new Date(), priority: 0.7 },
    // Blog subpages
    { url: `${baseUrl}/blog/benefits-classical-music`, lastModified: new Date(), priority: 0.6 },
    { url: `${baseUrl}/blog/chess-strategic-thinking`, lastModified: new Date(), priority: 0.6 },
    { url: `${baseUrl}/blog/theatre-confidence`, lastModified: new Date(), priority: 0.6 },
    { url: `${baseUrl}/blog/vedic-maths-tips`, lastModified: new Date(), priority: 0.6 },
    { url: `${baseUrl}/blog/creative-skills`, lastModified: new Date(), priority: 0.6 },
    { url: `${baseUrl}/blog/kathak`, lastModified: new Date(), priority: 0.6 },
    { url: `${baseUrl}/blog/guitar`, lastModified: new Date(), priority: 0.6 },
    { url: `${baseUrl}/blog/painting`, lastModified: new Date(), priority: 0.6 },
    { url: `${baseUrl}/blog/bharatanatyam`, lastModified: new Date(), priority: 0.6 },
  ];
}
